### ISSUE TITLE
The NDCG@3 dose not seem to work better than origin papter result.

### ISSUE THREAD

**Issue by 1141000271** [waterhorse1/MELU_pytorch#2]
I add the NDCG@3 metric for verification，but perform worse. Do you test the result with NDCG@3 metric? hope for you response.

**Comment by panghaoyu** [comment]
hi,
Could you please share the code for calculating NDCG, I am not sure how to calculate it in MeLU. Thank you.

**Comment by waterhorse1** [comment]
Recently I also tried to reproduce the result for calculating NDCG but failed. It seems the NDCG result in original paper is much higher than my experimental results.
