### ISSUE TITLE
Validation

### ISSUE THREAD

**Issue by mammadmaheri7** [waterhorse1/MELU_pytorch#7]
Hi. Thank you for sharing the code
I believe that you test the model and evaluate that with the same data used for training. Is it correct?
For cold start states it seems wrong in my opinion

**Comment by waterhorse1** [comment]
To be honest, I agree with you but it seems in original paper the warm-user-warm-iterm scenario is exactly trying to evaluate the same data used for training so we just follow their setting. I guess it may contain some information about training process. And I think the warm-user-cold-item scenario can really validate the results.
